Added argument validation to run script.

diff --git a/run_backend b/run_backend
--- a/run_backend
+++ b/run_backend
@@ -1,5 +1,23 @@
 #!/bin/bash
 
+usage="Usage: run_backend [dev|test] [--remove-prev]"
+
+# Argument validation
+case "$#" in
+    1) #
+    ;;
+    2) if [ "--remove-prev" != "$2" ]; then
+           echo "Error: Unknown argument: $2"
+           echo "$usage"
+           exit 1
+       fi
+    ;;
+    *) echo "Error: Illegal number of parameters."
+       exit 1
+    ;;
+esac
+
+
 extra_args=()
 if [ "test" = "$1" ]; then
     DATABASE_URL="postgresql://postgres:postgres@c_postgresdb_test:5433/ariavt"
@@ -15,10 +33,10 @@ elif [ "dev" = "$1" ]; then
         docker rm c_postgresdb
         docker volume rm postgres-data app-data
     fi
-elif [ "local" = "$1" ]; then
-    DATABASE_URL="postgresql://postgres:postgres@localhost:5433/ariavt"
 else
-    echo "Error: unknown database."
+    echo "Error: unknown option: $1"
+    echo "$usage"
+    exit 1
 fi
 
 echo "$DATABASE_URL" > app/database
